# Generated by Django 2.2.1 on 2019-05-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('genero', models.CharField(choices=[('Alternativo', 'Alternativo'), ('Blues', 'Blues'), ('Glam Metal', 'Glam Metal'), ('Hard Rock', 'Hard Rock'), ('Heavy Metal', 'Heavy Metal'), ('Rock', 'Rock'), ('Metal', 'Metal')], max_length=50)),
                ('integrantes', models.CharField(max_length=200, verbose_name='Integrantes')),
                ('fundacao', models.DateField()),
            ],
        ),
    ]
